Repository Final-Project-Team11/Meer_catlender_BE, pull requests merged in 2023-04, with the labels that each got.

#49 [fix]투두리스트 파일 분리 완료 #47
  controllers/myPage.controller.js
  controllers/todo.controller.js
  repositories/myPage.repository.js
  repositories/todo.repository.js
  routes/index.js
  routes/myPage.route.js
  routes/todo.route.js
  services/myPage.service.js
  services/todo.service.js
Labels: bug

#207 Fix/schedule
  README.md
  controllers/submit.controller.js
  middlewares/fileUpload.js
  models/files.js
  package-lock.json
  package.json
  repositories/submit.repository.js
  routes/submit.route.js
  schemas/submit.schema.js
  services/submit.service.js
Labels: fix

#231 [FIX] location 필수값 빼기 #224
  schemas/submit.schema.js
Labels: fix

#233 [FIX] mainPage Vacation 수정사항 변경 #224
  services/mainPage.service.js
Labels: fix

#241 [FIX] console.log #224
  repositories/mainPage.repository.js
Labels: fix

#246 [FIX] transactionError 콘솔 #224
  repositories/mainPage.repository.js
  repositories/submit.repository.js
Labels: fix

#248 [FIX] program -> event 바꾸기#224
  repositories/mainPage.repository.js
  services/mainPage.service.js
Labels: fix

#252 Fix/modify
  controllers/submit.controller.js
  repositories/submit.repository.js
  routes/submit.route.js
  services/submit.service.js
Labels: fix

#264 [TEST]관리자 미들웨어 테스트 코드 작성 #263
  middlewares/managerMiddleware.js
  package-lock.json
  package.json
  test/fixtures/userManage.fixtures.js
  test/unit/middlewares/managerMiddleware.test.js
Labels: test

#271 Features/main page test
  package.json
  test/fixtures/mainPage.fixtures.js
  test/unit/controllers/mainPage.controller.test.js
  test/unit/services/mainPage.service.test.js
Labels: fix

#279 Dev
  package-lock.json
  package.json
  repositories/submit.repository.js
  services/submit.service.js
  test/fixtures/mainPage.fixtures.js
  test/unit/repositories/mainPage.repository.test.js
Labels: test

#287 Fix/file location
  middlewares/fileUpload.js
Labels: fix
